/**
 * Creating a sidebar enables you to:
 - Create an ordered group of docs
 - Render a sidebar from the docs folder structure
 - Order your docs absolutely (without any automatic sorting)
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: {
        type: 'generated-index',
        title: 'Module 1: ROS 2',
        description: 'Middleware for robot control',
        slug: '/category/module-01-ros2',
      },
      items: [
        'module-01-ros2/01-ros2-concepts',
        'module-01-ros2/02-nodes-topics-services',
        'module-01-ros2/03-urdf-humanoids',
        'module-01-ros2/04-python-rclpy-bridge',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      link: {
        type: 'generated-index',
        title: 'Module 2: Simulation',
        description: 'Physics simulation and environment building',
        slug: '/category/module-02-simulation',
      },
      items: [
        'module-02-simulation/01-gazebo-fundamentals',
        'module-02-simulation/02-urdf-vs-sdf',
        'module-02-simulation/03-sensor-simulation',
        'module-02-simulation/04-unity-digital-twin',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      link: {
        type: 'generated-index',
        title: 'Module 3: NVIDIA Isaac™',
        description: 'Advanced perception and training',
        slug: '/category/module-03-isaac',
      },
      items: [
        'module-03-isaac/01-isaac-sim-overview',
        'module-03-isaac/02-synthetic-data-generation',
        'module-03-isaac/03-isaac-ros-vslam',
        'module-03-isaac/04-nav2-bipedal',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      link: {
        type: 'generated-index',
        title: 'Module 4: Vision-Language-Action',
        description: 'The convergence of LLMs and Robotics',
        slug: '/category/module-04-vla',
      },
      items: [
        'module-04-vla/01-whisper-voice-to-action',
        'module-04-vla/02-llm-task-planning',
        'module-04-vla/03-vision-language-action',
        'module-04-vla/04-capstone-autonomous-humanoid',
      ],
    },
    'hardware-requirements',
  ],
};

module.exports = sidebars;
